### ISSUE TITLE
Built-in resolver to call Rest API

### ISSUE THREAD

**Issue by daniel-duarte** [danielduarte/flowed#11]
Provide a built-in resolver to call a rest API.

**Comment by danielduarte** [comment]
Provided as Flowed plugins:
- [flowed-openapi](https://www.npmjs.com/package/flowed-openapi) An OpenApi resolver
- [flowed-http](https://www.npmjs.com/package/flowed-http) A generic HTTP/S resolver

Usage (example in TypeScript):
```typescript
import { FlowedPlugin } from 'flowed';
import FlowedOpenApi from 'flowed-openapi';

FlowManager.installPlugin(FlowedOpenApi as FlowedPlugin);

// All set to use the resolver name "flowed::OpenApi"!
```
It is pretty similar to integrate [flowed-http](https://www.npmjs.com/package/flowed-http).

Note that this solution is not included as a part of the package [flowed](https://www.npmjs.com/package/flowed) to preserve it as light as possible for those that does not need the HTTP feature. But as shown above, it is super easy to install and use.
