### ISSUE TITLE
Resolver as a functional component?

### ISSUE THREAD

**Issue by tarun29061990** [danielduarte/flowed#33]
**Is your feature request related to a problem? Please describe.**
I need to cal useQuery apollo hook and with resolvers as class components I am not able to do so.

**Describe the solution you'd like**
Library should accept resolver as simple functions also.

**Describe alternatives you've considered**
I tried to write resolver as a functional component but then it failed with error like "this.taskResolverConstructor is not a constructor".

**Comment by danielduarte** [comment]
Hi @tarun29061990,
I'll be working on supporting raw functions very soon since it seems to be useful for many use cases.
BTW I've already tracked that request [here](https://github.com/danielduarte/flowed/issues/10) before.

Make sure you watch this issue so you get the updates soon.

**Comment by tarun29061990** [comment]
Cool ... I will track the request

**Comment by danielduarte** [comment]
Hello @tarun29061990,

Here announcing that the last **Flowed** release `v1.14.0` includes support for functional resolvers. Class-based ones are also supported as in previous versions. Hope that helps!

Any question or concern please let me know.
