### ISSUE TITLE
Feeding the Conditional resolver true/false results without using parameters

### ISSUE THREAD

**Issue by dieeisenefaust** [danielduarte/flowed#41]
From the examples I have looked over and the testing I have run, it does not appear that trueResult/FalseResult parameters can be set to a hardcoded line of text, but have to be fed their values from an entry in the parameter object.

If you have a flow spec with multiple conditionals which each have different true/false results, it would be easier to be able to write those directly in the params instead of having to feed in multiple different key/value pairs in hte parameters object.

Ex.
```
          resolver: {
            name: 'flowed::Conditional',
            params: { condition: 'intervalsCreated', trueResult: 'This is the text for true' , falseResult: 'This is the text for false' },
            results: {onTrue: 'ontrue', onFalse: 'onfalse'},
          },
```

And/or also being able to reference values in the context object

Ex.
```
        resolver: {
          name: 'flowed::Conditional',
          params: { condition: 'intervalsCreated', trueResult: 'context.context_true' , falseResult: 'context.context_false' },
          results: {onTrue: 'ontrue', onFalse: 'onfalse'},
        },
```

**Comment by danielduarte** [comment]
Hi @dieeisenefaust,
You can set hardcoded values by using an object with the property `val` , just like in this example:

          resolver: {
            name: 'flowed::Conditional',
            params: {
              condition: 'intervalsCreated',
              trueResult: { val: 'This is the text for true' },
              falseResult: { val: 'This is the text for false' }
            },
            results: {onTrue: 'ontrue', onFalse: 'onfalse'},
          },

That way Flowed knows it has to be taken as a literal value.
Using a string, it is taken as a "token" to be taken from the `requires` clause.

**Comment by dieeisenefaust** [comment]
Should have tested this before responding but just a note that the property name needs to be `value`, not `val`, in the example above.
